export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS"
export const ADD_TO_COLLECTION = "ADD_TO_COLLECTION"

export const INIT_HOME_PRODUCT = "INIT_HOME_PRODUCT"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_FAVORITE = "ADD_FAVORITE"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"

export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"
